[package]
name = "content-hashing"
version.workspace = true
authors.workspace = true
description = "Encryption content, Hashing checking"
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
chacha20poly1305 = { version = "0.10.1", features = ["stream"] }
blake3 = "1.5.5"
futures = "0.3.31"
hex = "0.4.3"
libp2p = "0.54.1"
multihash = "0.19.3"
multihash-codetable = {version = "0.1.4", features = ["sha2"]}
rand = "0.8.5"
tokio = { version = "1.42.0", features = ["fs", "io-util", "full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
typenum = "1.17.0"